FROM registry.access.redhat.com/ubi8/ubi:8.8 as java-builder

# ARG JAVA_PACKAGE=java-17-openjdk-jmods
ARG JAVA_PACKAGE=java-17-openjdk-headless.x86_64
RUN yum -y update && \
    yum -y install --nodocs ${JAVA_PACKAGE} && \
    yum clean all && \
    rm -rf /var/cache/yum

# Build a custom JRE.
# For now, we will include all modules.  We could try to remove the ones
# we don't need to reduce image size and security attack surface.
WORKDIR /jrebuild
RUN java --list-modules | cut -d'@' -f1 > modules
RUN jlink --output runtime --add-modules `paste -sd, - < modules` --compress 2 --vm server

# Build a minimal base image with our custom Java installed.

FROM registry.access.redhat.com/ubi8/ubi:8.8 AS java-base
LABEL maintainer="OpsMx"
COPY --from=java-builder /jrebuild/runtime /opsmx-java-runtime
ARG OPSMXUSER=1001
ENV JAVA_HOME=/opsmx-java-runtime \
    PATH=${PATH}:/opsmx-java-runtime/bin \
    WORK_DIR=/opsmx/workdir \
    CONF_DIR=/opsmx/conf \
    SERVICE_PLUGIN_PATH=/opt/echo/plugins

# Enabling fips mode
RUN fips-mode-setup --enable

# Setting crypto policies to FIPS
RUN update-crypto-policies --set FIPS

COPY echo-web/build/install/echo /opt/echo
#RUN yum -y install java-17-openjdk-devel wget vim curl net-tools nettle

##CVE-2019-12900,CVE-2021-43618 

RUN dnf -y update  gnutls python3-idna python3-urllib3 libxml2 openldap sqlite-libs && dnf clean all

# Verify the updated versions
RUN rpm -q python3-urllib3 libxml2 openldap sqlite-libs 

# Install or upgrade Python (optional version 3.6 or 3.8)
RUN yum -y install python3 && yum clean all

# Verify Python version
RUN python3 --version

RUN yum -y install wget  bzip2-libs-1.0.6-28.el8_10 -y
RUN yum install ca-certificates-2024.2.69_v8.0.303-80.0.el8_10  gmp-6.1.2-11.el8 -y


RUN wget https://tsn.miraclelinux.com/system/files/AXS8/x86_64/UPDATE/RPMS/expat-2.2.5-16.el8_10.x86_64.rpm
RUN rpm -Uvh --force expat-2.2.5-16.el8_10.x86_64.rpm

RUN wget https://fr2.rpmfind.net/linux/almalinux/8.10/BaseOS/x86_64/os/Packages/krb5-libs-1.18.2-30.el8_10.x86_64.rpm
RUN rpm -Uvh --force  krb5-libs-1.18.2-30.el8_10.x86_64.rpm 




#RUN yum -y update
RUN adduser spinnaker
RUN mkdir -p ${SERVICE_PLUGIN_PATH}

#custom plugin zip files adding

ARG CUSTOMPLUGIN_RELEASE_VERSION
ENV CUSTOMPLUGIN_RELEASE_VERSION=$CUSTOMPLUGIN_RELEASE_VERSION
ARG CUSTOMPLUGIN_RELEASEVERSION_PLUGIN
ENV CUSTOMPLUGIN_RELEASEVERSION_PLUGIN=$CUSTOMPLUGIN_RELEASEVERSION_PLUGIN
ARG CUSTOMPLUGIN_RELEASEORG
ENV CUSTOMPLUGIN_RELEASEORG=$CUSTOMPLUGIN_RELEASEORG
ARG CUSTOMPLUGIN_RELEASEREPO
ENV CUSTOMPLUGIN_RELEASEREPO=$CUSTOMPLUGIN_RELEASEREPO


RUN wget -O Opsmx.EchoEventPlugin-EchoEventPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c https://github.com/${CUSTOMPLUGIN_RELEASEORG}/Customplugins/releases/download/v${CUSTOMPLUGIN_RELEASEVERSION_PLUGIN}/EchoEventPlugin-v${CUSTOMPLUGIN_RELEASE_VERSION}-SNAPSHOT.zip -P ${SERVICE_PLUGIN_PATH}
RUN mv Opsmx.EchoEventPlugin-EchoEventPlugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip ${SERVICE_PLUGIN_PATH}


RUN wget -O Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip -c https://github.com/${CUSTOMPLUGIN_RELEASEORG}/${CUSTOMPLUGIN_RELEASEREPO}/releases/download/v${CUSTOMPLUGIN_RELEASE_VERSION}/armory-observability-plugin-v${CUSTOMPLUGIN_RELEASE_VERSION}.zip -P ${SERVICE_PLUGIN_PATH}
RUN mv Armory.armory-observability-plugin-${CUSTOMPLUGIN_RELEASE_VERSION}.zip ${SERVICE_PLUGIN_PATH}

RUN chmod -R 777 ${SERVICE_PLUGIN_PATH}
RUN chown -R spinnaker:spinnaker /opt/

RUN yum -y remove  tar  vim vi
RUN yum -y remove clean all && rm -rf /var/cache

USER spinnaker
CMD ["/opt/echo/bin/echo"]
